spring:
  server:
    port: 5000
  multipart:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
  redis:
    host: localhost
    port: 6379
#    flush-mode: on-save